Input shape verification for convolutional models
meteofrance/mfai pull request #10
Opened 2024-11-22 12:39 UTC by MicheleCattaneo

### What does this PR do?
It introduces utilities to handle invalid input shapes for convolutional models. 

### Current progress
- [x] Functions to check the input shapes for `UNet`, `HalfUNet` and `CustomUNet` + tests.
- [x] Padding and un-padding functions to be used in conjunction with the aforementioned ones + tests.
- [ ] Automatic padding for torch lightning modules exposed through their settings.

### Related Issue

closes #9 

This draft PR will be updated as the work progresses. Please share any feedback on the overall structure.

2024-11-22 14:31 UTC, LBerth reviewed
Hi !
Very good job and very nice first contribution.
I have only 2 minor comments concerning the unit test of the padding.
Léa

2024-11-22 14:33 UTC, MicheleCattaneo commented on tests/test_utils.py
Good point, I will do it.

2024-11-22 14:36 UTC, MicheleCattaneo commented on tests/test_utils.py
> +    padded_data = pad_batch(batch=data, new_shape=new_shape, pad_value=0)
I was afraid to not cover some edge cases  for odd/even sizes by keeping the sizes fixed. I am not sure if it's a good approach, but if there is an issue, it should come up with time (as tests are run multiple times).

2024-12-11 16:38 UTC, colon3ltocard commented
Hi again @MicheleCattaneo ,

Sorry for the late reply we went thru a lot of changes before being able to integrate/discuss new features.

We discussed with the team and we have some suggestions to make for the autopad you propose:
* Separation Of Concern: auto-padding is only meaningful for a subset of the models so it should not "contaminate" outside the subset of models (the actual ModelABC subclasses) it is related to.

We propose that a model able to autopad should expose it thru extra settings, here is an example with HalfUnet:

```python
@dataclass_json
@dataclass(slots=True)
class HalfUNetSettings:
    num_filters: int = 64
    dilation: int = 1
    bias: bool = False
    use_ghost: bool = False
    last_activation: str = "Identity"
    absolute_pos_embed: bool = False
    autopad: bool = False
 ```
 
 Now the model can handle this in its forward method (this code could be factored in a common class or Mixin):
 
 ```python
 def forward(self, x):
      if self.settings.autopad:
           x = self.pad(x)
           y=self._forward(x)
           return self.unpad(y)
      else:
         return self._forward(x)
```
Note : i omitted the shape tracking on purpose for the brevity of this.

This way the autopad doesn't "pollute" the Segmentation/Regression lightning, we don't have to check if autopad is supported using dedicated code outside the model and we can also use it transparently in pure PyTorch loops.

2024-12-13 09:31 UTC, MicheleCattaneo commented
Hi @colon3ltocard, 
I agree with what you suggest. Commit [337ef25](https://github.com/MicheleCattaneo/mfai/commit/337ef2529ceacb33020d7fc6c316affa5d14605e) implements a first variant of this idea. Let me know if you have any feedback!

2025-01-06 15:35 UTC, colon3ltocard commented on mfai/torch/models/unet.py
> +        return len(re.findall(r'max_pool\(', source_code))
maybe use a cachedproperty ? we probably don't want to inspect source code at each call.

2025-01-06 15:37 UTC, colon3ltocard commented on mfai/torch/models/half_unet.py
> +class HalfUNet(ModelABC, nn.Module, AutoPaddingModel):
For the sake of clarity I would put the two ABCs first:

```suggestion
class HalfUNet(ModelABC, AutoPaddingModel), nn.Module):
```

2025-01-06 15:39 UTC, colon3ltocard commented on mfai/torch/models/unet.py
> +class CustomUnet(ModelABC, nn.Module, AutoPaddingModel):
```suggestion
class CustomUnet(ModelABC, AutoPaddingModel, nn.Module):
```

2025-01-06 15:45 UTC, colon3ltocard commented
@MicheleCattaneo A few minor comments + some CI fails and then we can merge :+1:

2025-01-07 10:11 UTC, colon3ltocard commented on mfai/torch/models/base.py
> +        if self.autopad_enabled and old_shape is not None:
```suggestion
        if self._settings.autopad_enabled and old_shape is not None:
```

2025-01-07 10:11 UTC, colon3ltocard commented on mfai/torch/models/unet.py
> +        self.autopad_enabled = settings.autopad_enabled
```suggestion
```

2025-01-07 10:13 UTC, colon3ltocard requested changes
One last comment: directly reference the self._settings for the autopad_enabled bool

2025-01-07 13:43 UTC, MicheleCattaneo reviewed
Done 👍

2025-01-07 14:30 UTC, colon3ltocard approved these changes

2025-01-07 14:30 UTC, colon3ltocard approved these changes

2025-01-08 08:28 UTC, LBerth approved these changes
Hi ! Very good contribution, thank you Michele ! :)

2025-01-08 08:28 UTC, merged